name: "React App"

on:
 push:
   branches:
      - main
 workflow_dispatch:


jobs:
  build:                      
    runs-on: [self-hosted]
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Environment
        run: echo ${{ secrets.Env_Name }}

  test:                     
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Npm Install 
        run: npm ci
      - name: Npm Build
        run: npm run build
      


      
  
